### ISSUE TITLE
Was working great and now won't authorise on 3456

### ISSUE THREAD

**Issue by plasterer41** [cakebake/node-red-contrib-alexa-remote-cakebaked#22]
Any thoughts or any similar experiences?

thanks,

Irwin

**Comment by datbilling** [comment]
I have the same problem as of yesterday. I get Authentication failed: “no body”. Occasionally it seems to succeed.

**Comment by notownblues** [comment]
Same here, Authentication failed: “no body” most of the time after Node-Red restart or Re-innitialised.

**Comment by Toxo666** [comment]
Same here. Tested with varoius port.
I have compared an old session file and a new, there r differences.
The old on work as normal (second amazon acc on 3457).

With "node-red-contrib-alexa-remote-fork" & "node-red-contrib-alexa-remote2-v2" same problems.
No body

**Comment by andesse** [comment]
Same problems. I need to reply the process about 15 times until I get ready/success on my init nodes. Appeared two days ago for the first time.

**Comment by kmorrow429** [comment]
Having the same issue. Have to set my initialize flow on a catch error loop until it starts working. Sometimes it takes several hours before it is successful

**Comment by notownblues** [comment]
@kmorrow429 if you don't want to wait for hours I found that if you edit the account, don't change any setting, just update then redeploy it eventually works again after 5-10 minutes

**Comment by andesse** [comment]
If it's initialized, you have the cookie in a textfile and everything is ok, how long will it stay in this state? Anyone knows?

**Comment by notownblues** [comment]
@andesse for me it stays initialised unless I restart Node Red, Deploy any of the Alexa Remote2 nodes or Reinitialise (I've got a flow that réinitialises automatically if some speak routines don't work anymore), usually happens every 3 days

**Comment by kmorrow429** [comment]
@notownblues I had tried that, but when it didn't work immediately I tried deleting the auth file and a couple of restarts. If it happens again, I'll try that and leave it for a while to see if it works

**Comment by GurjBahia** [comment]
Same problem here (in the UK) for the last couple of days. Authenticates fine after several manual restart flows and manual injected initialise attempts. But the next time it tries to refresh (I have it timed for once an hour) it fails again.

Errors I see are mostly "Authentication failed: "no body"" and separately "failed to load routines: "routines.map is not a function""

**Comment by BrigHubert** [comment]
Exactly the same Problem in Germany (Service Host: layla.amazon.de)

**Comment by andesse** [comment]
Question:
Does it appear maybe when you run two alexa accounts in node red? I just added a second one to Node-Red one day before this problem happened. I am not at home since three days, so I can't try it out. Btw, I'm from Germany.

**Comment by Thymos2k** [comment]
> Question:
> Does it appear maybe when you run two alexa accounts in node red? I just added a second one to Node-Red one day before this problem happened. I am not at home since three days, so I can't try it out. Btw, I'm from Germany.

No, I am only using one account and have the same problem. I am from germany, too.

**Comment by BrigHubert** [comment]
> Question:
> Does it appear maybe when you run two alexa accounts in node red?

No, I have only one alexa account. Same Error after Deactivation of 2fa in Alexa. Setting "Auto Init" to off in Node-RED-Alexa Configuration-Node and Using Node "Alexa init" solves the problem only one times.

**Comment by andesse** [comment]
> Updating the alexa-remote2 dependency to v3.8 should do the trick.

Which contrib is it?

**Comment by andesse** [comment]
> Updating the alexa-remote2 dependency to v3.8 should do the trick.

Which contrib is it?

**Comment by andesse** [comment]
> Updating the alexa-remote2 dependency to v3.8 should do the trick.

Wich contrib do you use?

**Comment by BrigHubert** [comment]
> Updating the alexa-remote2 dependency to v3.8 should do the trick.

I'm using "node-red-contrib-alexa-cakebaked" V. 4.0.2. On GitHub this Version is commented with "Updates dependency alexa-remote2 to v3.7.1". I alredy searched for newer Versions, but I didn't found one. Where can I get v3.8?

**Comment by BrigHubert** [comment]
Thank you, andesse. If no one will find a workaround, I wait and hope, the developer resolves the problem.

**Comment by peteakalad** [comment]
Are you sure 3.8 fixes it?  I've been running it over a week have been experiencing the same "Authenication Failed: No Body" errors.

**Comment by BrigHubert** [comment]
I tried "3.8" today without success.

**Comment by bbindreiter** [comment]
So I've debugged the Authentication HTTP Requests and they suddenly respond with 503 'Service Unavailable' on `/api/bootstrap?version=0`. 

Not sure if this is because they've changed something in their API or because it really is unavailable, but I'm afraid it's the former.

**Comment by bbindreiter** [comment]
Found the issue. The Accept header is not sent in the request. As suspected, the issue is in `alexa-remote2` not here. I'll make a PR there shortly.

If you don't want to wait find this file `.node-red/node_modules/alexa-remote2/alexa-remote.js` and add `'Accept': 'application/json',` to the headers. That would be in line 797. After adding this and restarting node-red (so that it picks up the changes) it works again for me.

Example:
```
let options = {
            host: flags.host || this.baseUrl,
            path: '',
            method: 'GET',
            timeout: flags.timeout || 10000,
            headers: {
                'User-Agent' : this._options.userAgent,
                'Content-Type': 'application/json; charset=UTF-8',
		'Accept': 'application/json',
                'Referer': `https://alexa.${this._options.amazonPage}/spa/index.html`,
                'Origin': `https://alexa.${this._options.amazonPage}`,
                //'Content-Type': 'application/json',
                //'Connection': 'keep-alive',
                'csrf' : this.csrf,
                'Cookie' : this.cookie,
                'Accept-Encoding': 'gzip,deflate'
            }
        };
```

**Comment by andesse** [comment]
@bbindreiter thanks! Awesome you figured it out!

**Comment by notownblues** [comment]
> Found the issue. The Accept header is not sent in the request. As suspected, the issue is in `alexa-remote2` not here. I'll make a PR there shortly.
> 
> If you don't want to wait find this file `.node-red/node_modules/alexa-remote2/alexa-remote.js` and add `'Accept': 'application/json',` to the headers. That would be in line 797. After adding this and restarting node-red (so that it picks up the changes) it works again for me.
> 
> Example:
> 
> ```
> let options = {
>             host: flags.host || this.baseUrl,
>             path: '',
>             method: 'GET',
>             timeout: flags.timeout || 10000,
>             headers: {
>                 'User-Agent' : this._options.userAgent,
>                 'Content-Type': 'application/json; charset=UTF-8',
> 		'Accept': 'application/json',
>                 'Referer': `https://alexa.${this._options.amazonPage}/spa/index.html`,
>                 'Origin': `https://alexa.${this._options.amazonPage}`,
>                 //'Content-Type': 'application/json',
>                 //'Connection': 'keep-alive',
>                 'csrf' : this.csrf,
>                 'Cookie' : this.cookie,
>                 'Accept-Encoding': 'gzip,deflate'
>             }
>         };
> ```

Just did the above and it now works perfect again. Thank you so much @bbindreiter!

**Comment by fmarzocca** [comment]
@bbindreiter thanks

**Comment by peteakalad** [comment]
Confirm working with above Accept header change here too.  Cheers @bbindreiter

**Comment by andesse** [comment]
What I am really curious about is, why did it worked for a quiet long time and now was suddenly broken...

**Comment by peteakalad** [comment]
I'd guess it'll be down to Amazon changing their services breaking the requests the remote2 lib makes.

**Comment by GurjBahia** [comment]
Hmm, think I was too quick to say the header change works for me. It may have just worked once.
Will look at doing a clean install in the next few days to see if that helps.

**Comment by gaussey** [comment]
@bbindreiter Thank you so much!

**Comment by BrigHubert** [comment]
@bbindreiter Thank you!

**Comment by stingrayuk** [comment]
@bbindreiter Thank you so much, been fighting with this for a few days :-)

**Comment by obaldius** [comment]
@bbindreiter thanks a lot my man, If it weren't for you guys I wouldn't have a smart home, ty really

**Comment by GioDoe** [comment]
Thank you, it works like a charm!

**Comment by bwims** [comment]
@bbindreiter you are a hero!

**Comment by Apollon77** [comment]
alexa-remote 3.8.1 is coming to npm just now. Have fun and thank you @bbindreiter

**Comment by Matten-Matten** [comment]
@bbindreiter  Großen Dank auch von mir!

Gruß Matten Matten

**Comment by bbindreiter** [comment]
Thank you very much everyone. Let's hope for an updated version soon.

**Comment by woody4165** [comment]
Unfortunately, for me it's not working.
I still get the `Authentication failed: "No body"` message.
After I go to the IP:3456 to authenticate with my credentials, it seems that it does not create the cookie file and after `Initialise`, I get again the message to go the IP:3456 page

**Comment by Matten-Matten** [comment]
@woody4165 
Nodered restartet?

**Comment by woody4165** [comment]
Yes, I have NR in a Proxmox Container and I did first a `service nodered restart` and also a `reboot` after.

**Comment by Matten-Matten** [comment]
strange, you are also sure that the files (3) have also been overwritten?

Gruß
Matten Matten

**Comment by woody4165** [comment]
Ops.....
I was modifying a copy of the `alexa-remote.js` file and not the one in the `.node-red/node_modules/alexa-remote2`

So, now all is working fine!

**Comment by saviothecnic** [comment]
I also have the same problem Accaunt Alexa Italia
in addition to me when I restart even before it does not keep me authenticating I have Domoticz and red node on a raspberry
and as a path I went to /home/pi/cookie/alexa.cookie

**Comment by bwims** [comment]
> I also have the same problem Accaunt Alexa Italia
> in addition to me when I restart even before it does not keep me authenticating I have Domoticz and red node on a raspberry
> and as a path I went to /home/pi/cookie/alexa.cookie

Have you followed the instructions here ?
https://github.com/cakebake/node-red-contrib-alexa-remote-cakebaked/issues/22#issuecomment-853171093

**Comment by saviothecnic** [comment]
> 
> Have you followed the instructions here ?

No sorry I'm Italian and I'm using google translator to understand
and maybe I missed something

I don't use alexa-remote2
but node-red-contrib-alexa-cakebaked 4.0.2 i believed that solution was for remote2 not cakebaked

**Comment by obaldius** [comment]
@saviothecnic follow the instructions, I'm using cakebaked and it's worked for me

**Comment by saviothecnic** [comment]
ok i removed
node-red-contrib-alexa-cakebaked 4.0.2
and installed node-red-contrib-alexa-remote2-v2
and modified as you suggested it now works again Only that at every restart it always asks me to re-authenticate but only if I restart raspberry my cookie path is this
/home/pi/cookie/alexa.cookie

**Comment by andesse** [comment]
I am to stupid to find the file. 
My system is Raspberrymatic based Redmatic. Can someone help me and comment the path that I need to use in ssh to find It? 
Thanks in advance

**Comment by bwims** [comment]
It might be

/usr/local/addons/redmatic/var/node_modules/node-red-contrib-opcua/node_modules


I did Google Redmatic "path" to "node-red" modules   (Did you try that?)

and found this

https://github.com/mikakaraila/node-red-contrib-opcua/issues/193

Can't help you otherwise.

**Comment by bbindreiter** [comment]
@cakebake hasn't been active since the beginning of February. I'm not sure if he's still using this node at all otherwise he'd have written something in here 🤷‍♂️ 

Even though I want to avoid it if somehow possible, maybe it's time to fork this node once again. I'm sure there are people out there not finding their way to github and are getting frustrated.

**Comment by bwims** [comment]
> @cakebake hasn't been active since the beginning of February. I'm not sure if he's still using this node at all otherwise he'd have written something in here 🤷‍♂️
> 
> Even though I want to avoid it if somehow possible, maybe it's time to fork this node once again. I'm sure there are people out there not finding their way to github and are getting frustrated.

I already said you were a hero! 🙂

**Comment by andesse** [comment]
@bwims thanks, found it at the end... Not the best in console using 🤣

**Comment by andesse** [comment]
@bbindreiter just fork it. 
I personally, as an "end consumer" am just happy when I have a contrib that runs stable and gets a new update if not so :)

**Comment by peteakalad** [comment]
Sad to say but it needs to be forked (again).  

It needs a maintainer who has the time/attention to up version when the key dependency (alexa-remote) gets updates.

Unfortunately @cakebake mustn't have this time/attention, evidenced by the multiple releases of alexa-remote since 18 April v3.7.2 with no version update here.  I'd really rather be getting updates via the node red palette manager than hacking at node modules.

**Comment by bwims** [comment]
ditto!

**Comment by saviothecnic** [comment]
And it is true there are 4 versions that are photocopies of each other
and it just creates confusion I see that some are updated for 11 months others for 4 months others for 2 months another for 1 month
we all automation enthusiasts have alexa and being able to plagiarize it for our purposes thanks to the red knot is very nice
but you need a knot that always stays in step with adj
by Amazon Alexa

**Comment by team-tech-works-uk** [comment]
this is *pretty much* one of the _most-important_ (for me - and others?) node-red modules - alexa has gained imho dominance as an intelligent UI for smart-homes and hence strong and *reliable* integration with node-red is essential.  I'd be happy to *pay* a suitable maintainer (or even offer my services if all else fails!!!)

**Comment by Chris380** [comment]
@bbindreiter Vielen Dank Bernd, tolle Arbeit!!
I've added the accept property in line 797 and restarted node-red, everything works fine again. I wish I had found this issue and your solution a bit earlier. I was getting frustrated, because redeploying, reinitializing, restarting did not help since a few day.

**Comment by Matten-Matten** [comment]
Maybe we should then create a community node together.

Because many are very attentive here and also able to create a development like this.
In my opinion it is always difficult for one person to keep the node up to date (time, implementation, etc.)

Recently, the most common cause of bugs is the cookie thing, because of that I have subscribed the topic "alexa-remote / releases"  by @Apollon77, so I can implement innovations in my system.

At this point I have to say, that @Apollon7 does a first class job. Biggest thanks!

**Comment by bbindreiter** [comment]
Good, I'll fork it. Maintainers and contributors welcome. Will post the link here shortly.

**Comment by cakebake** [comment]
Hi! Sorry for the late reply. I had forked the project mainly for myself and hadn't used it in the last few weeks.
I think it's great that the community proves itself here once again and that people help each other.
If I can help with the new fork, please let me know.
Otherwise I can also include other developers here. That would save many having to reinstall the node.
I'm happy to report. I am subscribed.

**Comment by bbindreiter** [comment]
Hi @cakebake. Glad you're back! I absolutely agree that it would be best if we can just keep this fork here alive. Reinstalling is a pain. But eventually, that'd still mean that you're the one who has to do the builds and uploads to npmjs and nodered. Do you have the time and energy for it?

**Comment by cakebake** [comment]
> But eventually, that'd still mean that you're the one who has to do the builds and uploads to npmjs and nodered. Do you have the time and energy for it?

Hi @bbindreiter,

That's right ... time is always a problem for me...

It would be incredibly helpful if you would check the functionality and if you can also resolve the merge requests. In terms of quality, it generally makes sense for one or two persons to do the "final acceptance" and publish the release. I can also hand over / share this process after a short time.

I am currently no longer using the node myself. But that can change again. :)

So if I have support on GitHub, I would be very helpful. This concerns issues, upstream keep an eye on, merge requests...

**Comment by andesse** [comment]
@bbindreiter @cakebake 
Jens, if you don't use the node anymore and time is short, hand it directly over to Bernd, he can create a new name for the contrib and is able to publish new releases. 

You can still participate if time is available, or helping with the final acceptance. 

Changing the contrib in node red isn't that complicated at all. 

Just came into my mind. Good idea?

**Comment by fmarzocca** [comment]
@andesse, but this would imply that all users will have to remove cakebaked
module, reinstall and configure a new one.

**Comment by andesse** [comment]
@fmarzocca thats so easy.
Backup all flows, delete everything, delete the contrib, install the new one, import everything. Takes 3 minutes.

But you are right, I get your point, it might be annoying for some users.

**Comment by bwims** [comment]
Don't forget the little wrinkle where deleting and reimporting a flow loses the authentication unless you fiddle with credential encryption etc.   

I'd much rather keep the same fork if at all possible, but also happy to move to another if necessary.

This is the missing software that Amazon should provide.  It turns a pretty useless voice automation system into something really powerful.

**Comment by bbindreiter** [comment]
Now that users can update `cakebaked` and find a working environment again there's no need to fork and migrate all users to a new node. I did create a fork here https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel which I intend to use for myself, as I'm eager to add more functionality, e.g. https://github.com/586837r/node-red-contrib-alexa-remote2/pull/181 . If something breaks I will always try to fix it upstream and support @cakebake, so everyone benefits from it.

Cheers!

**Comment by ammawel** [comment]
hmmm... of course first of all thank you very much for your efforts!

You write "as I'm eager to add more functionality" - and how will the rest of us users get this new functionality? 
Wouldn't it make more sense to have several developers like you working together on just one fork? Maybe also with a new name for the common project?

Maybe it would also be possible to work together to fix bugs that have been there for a long time.
For example, Alexa still stops talking after some time (only for some users? Why?). In the meantime, the error can be detected and the module reinitialized; other software that works similarly (FHEM) or even uses the same module from Apollon77 (iobroker) do not have this error. 

In its current form, despite the updates, this module is not reliable and actually not usable.
We still hope...

Thanks and regards
Achim

**Comment by bbindreiter** [comment]
I've been using this node for quite a while and found it very reliable actually. The only problem we all had was that it stopped working a while ago due to the authentication error, which is fixed now.

We all depend from alexa-remote2 and @Apollon77 is responsive. It was a matter of 24 hours to get the fix merged and published. Then it's up to the maintainers. Like previously pointed out, it doesn't help having multiple developers when only the owner is able to publish a new version to the repository. @cakebake stated that he's currently not using the node, therefore I have forked his repository so I can add new functionality and can independently publish to npmjs. The latter is important to me as I'm using this node heavily and rely on it (Doorbell, etc.. ). If there's something to fix I'll be the first to open a PR so users of `cakebaked` won't be left out.

**Comment by ohrenweide** [comment]
> therefore I have forked his repository so I can add new functionality and can independently publish to npmjs

This also seems to me to be the best solution. Thank you for your good work and help here.
I am very much looking forward to the fact that with the help of your project the textCommand will be available soon. This will allow any dynamic requests to be made to Alexa - this is the biggest step forward in a long time in my eyes.

**Comment by Matten-Matten** [comment]
Text to command is even a problem solver for me. Because I also set the alarm clock via the node, but unfortunately I have not yet succeeded, no matter how I format the input, to set an alarm clock longer than 24 hours and I think that is still a bug in the node.
 Since I manually inserted the text to command in my system, I was already able to test it and also solve my problem with the alarm clock.

**Comment by andesse** [comment]
@Matten-Matten is there a documentation how text-to-command is used?

**Comment by Matten-Matten** [comment]
`is there a documentation how text-to-command is used?`

to operate? that's easy you can enter what you can ask alexa too.

if you want to add the function in your node you have to do this manually in the files or wait until it appears here as an update.

greeting

**Comment by andesse** [comment]
@Matten-Matten gotcha! There is a workaround for doing this already. In the alexa app you can define a routine, where the trigger is what you actually would have asked alexa.

**Comment by cakebake** [comment]
> I've been using this node for quite a while and found it very reliable actually. The only problem we all had was that it stopped working a while ago due to the authentication error, which is fixed now.
> 
> We all depend from alexa-remote2 and @Apollon77 is responsive. It was a matter of 24 hours to get the fix merged and published. Then it's up to the maintainers. Like previously pointed out, it doesn't help having multiple developers when only the owner is able to publish a new version to the repository. @cakebake stated that he's currently not using the node, therefore I have forked his repository so I can add new functionality and can independently publish to npmjs. The latter is important to me as I'm using this node heavily and rely on it (Doorbell, etc.. ). If there's something to fix I'll be the first to open a PR so users of `cakebaked` won't be left out.

Hi @bbindreiter, 

I think you misunderstood me. I wanted to share this project with other developers so that "normal users" don't have to put in a lot of effort to redo their flow. That was very difficult for many of them the last time they made the switch.

If you have now made the decision to continue the project in a different repo, then syncing both projects makes absolutely no sense, as I then no longer see the purpose of keeping this project alive. Or am I seeing something wrong here? Nobody can benefit from it.

I can then rather write a simple guide on how everyone can "simply" create their fork in order to be able to be independent. The basic idea of ​​community is then no longer really given. Although it would certainly be instructive for many to know the code in connection with their Amazon account. No NPM repos or the Node-Red repository are required to install a node. This can also be done "simply" via the package.json of the Node-Red installation via Git.

Your decision. I'll just have a look here again soon and I'm happy to give authorizations to the source code or support another project if there is time and help is needed.

**Comment by bdydrp** [comment]
I have updated to the latest version, but still encounter a 'unexpected end of JSON input'
I believe this is because i use an Australian account

**Comment by vbenhur** [comment]
The problem came back to me. The fault Authentication Failure: "no body" appears after I restart the NR. 
When I log into amazon everything looks OK but after deploy or restart NR the error message appears.
I'm already using the latest version.

**Comment by andesse** [comment]
@vbenhur after a restart it's always necessary to make a fresh auth. Don't deploy full Flows, is that maybe the problem? If the auth and Init nodes get deployed, they cause the problems. 
I changed my deploys to changed nodes, and never had a problem since. 

important is also that you run all automations in a routine node. There choose the option "node" and Run all stuff that you need. you can choose serial to run several automations after another. 

if you trigger two alexa nodes in a flow simultaneously, the no json error usually appears in one or both. 

can these tips solve your issue?

maybe you're right and we have another problem yet, since when did it appear? I played with big automation today, used the routine nodes like described and had zero issues. I can't reproduce. 

Greetings

**Comment by andesse** [comment]
@vbenhur sorry, I use the applestrudel contrib, not the cakebaked anymore. 

maybe it helps to switch to this one. but try the tips I recommend first. maybe it works for you

**Comment by vbenhur** [comment]
@andesse thanks for the tips!
I didn't know the fact after a restart it's always necessary to make the authentication. It is a problem for me because I have a system running in a customer's house, then yesterday he had an energy fault and the system didn't come back. 
About node deploy, I just did it. It's a very interesting approach.
In my case, I am not triggering two Alexa nodes in a flow.

I installed the applestrudel contrib just to check if the error persists and the behavior remains the same.

But maybe there's nothing wrong with contrib if this authentication condition is always required on system reboot.
Is there some other solution to auto auth with cookie? I thought the cookie was for that.

**Comment by Matten-Matten** [comment]
Wenn du den Cookie in einer datei auf dem speicher speicherst und in der Konfiguration von node angibst. Ist nach einem Neustart keine Notwendigkeit das ganze zu Authentifizieren.

EN: If you save the cookie in a file on the memory and specify it in the configuration of node. After a restart there is no need to authenticate the whole thing.

Gruß
matten matten

**Comment by andesse** [comment]
@Matten-Matten @vbenhur 
oh sorry, I meant an initialize after reboot, my bad. 

but all main problems disappeared not deploying the nodes anymore.
deploying just changed nodes was a lifechanger. 

and important, don't trigger two nodes at the same time. 

fun fact: as I use Spotify in my bathroom, when the door closes, I had it on one Spotify account all the time. so the music everywhere else stopped when in use. 
first I contacted Amazon, asked if it's fine to make a second account on my name for the automation reason, they said: you can create as much accounts as you want. 
then I contacted Spotify, explained the reason, they said it's ok to run family accounts on different Echos in the same apartment and upgraded to a family account. 
now I have two Amazon account, feedet with different Spotify accounts. I can trigger these two account simultaneously in node red. no issue :)
I have one Spotify connected to the bathroom, one to the Livingroom. bathroom runs completely on its own play my Playlist, that have really Stange names, so the dot can find it and I can add new songs when I want. the second my Echo-dot, that is normally connected to my main account can be controlled with my ipad when it plays music. all very conviniet.

**Comment by bbindreiter** [comment]
In addition to Auto-Init with the cookie file I am running the Initialize node every hour because I also had issues in the past. 

![image](https://user-images.githubusercontent.com/3252801/135148360-d9ce61c7-b2fd-4b27-9825-69d79d4a7d9f.png)

I let Alexa tell me the time on every full hour during the day and it maybe didn't work once in the last 2 months.

**Comment by saviothecnic** [comment]
Guys to me for a few days is not working
is it just my problem or is it not working for you too?

**Comment by andesse** [comment]
> Guys to me for a few days is not working
> 
> is it just my problem or is it not working for you too? 

This contrib isn't updated anymore when I am right. You can use the Applestrudel one. This works fine. 
it's a fork from the cakebaked. 
BACKUP your flows, delete your flows, deinstall cakebaked, reboot, install Applestrudel, Import your flows

**Comment by saviothecnic** [comment]
Thanks I didn't know about the new fork
I switched to Applestrude but I still have it
the same problem ie it works to feel
but it doesn't work for me to talk about alexa

**Comment by andesse** [comment]
> Thanks I didn't know about the new fork
> 
> I switched to Applestrude but I still have it
> 
> the same problem ie it works to feel
> 
> but it doesn't work for me to talk about alexa 

can you describe your problem a little bit more detailed?

**Comment by andesse** [comment]
> In addition to Auto-Init with the cookie file I am running the Initialize node every hour because I also had issues in the past. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3252801/135148360-d9ce61c7-b2fd-4b27-9825-69d79d4a7d9f.png)
> 
> 
> 
> I let Alexa tell me the time on every full hour during the day and it maybe didn't work once in the last 2 months.
> 
> 

@bbindreiter 
Hey, I just figured recently out that I only have problems when 2 Alexa Nodes are running simultaneously. Since I am using the Node Alexa Routine, in the settings "Node" with the setting "serial" and add any Number of requests inside, I have no problems at all. Changed some flows using this rule and everything works perfect. 
Also I asked Amazon, it's ok to run several Accounts just for using Alexa. Some rooms also have a different Account. 
I just initialize after Node-Red reboot.

**Comment by Chris380** [comment]
Some minutes ago I switched from _node-red-contrib-alexa-remote-cakebaked_ to _node-red-contrib-alexa-remote2-applestrudel_   with the ui migration (deleting and reimporting the flows). I can confirm that applestrudel works fine.
Glad to see now that I can use _Device Activity_ again.
Danke @bbindreiter für Deinen Einsatz :-)

**Comment by saviothecnic** [comment]
> can you describe your problem a little bit more detailed?

![NodeRedErrore](https://user-images.githubusercontent.com/6697807/137489167-d6e7d554-dda0-46b4-a8f3-9f2f178d279c.jpg)

Example in this node I ask
alexa the temepratura alexa hears the request
but it doesn't tell me the temperature on the device
I know that the request is heard because the answer
that I also send on telegram I find it
but I am not speaking from the paired echo device

**Comment by andesse** [comment]
> > can you describe your problem a little bit more detailed?
> 
> 
> 
> ![NodeRedErrore](https://user-images.githubusercontent.com/6697807/137489167-d6e7d554-dda0-46b4-a8f3-9f2f178d279c.jpg)
> 
> 
> 
> Example in this node I ask
> 
> alexa the temepratura alexa hears the request
> 
> but it doesn't tell me the temperature on the device
> 
> I know that the request is heard because the answer
> 
> that I also send on telegram I find it
> 
> but I am not speaking from the paired echo device 
> 
> 

@saviothecnic 
try to use a delay node with 1 second before the routine speak node. 
did you debug what comes out of the first function node? does the format fit for the alexa node?

**Comment by saviothecnic** [comment]
I'm sorry I'm not very experienced can you give me an example on how to delay?

**Comment by saviothecnic** [comment]
I did this but it doesn't work 

![NodeRedPausa](https://user-images.githubusercontent.com/6697807/137498604-6ca81fbf-723b-4e6f-b0f1-d6bccdd11595.jpg)

**Comment by bbindreiter** [comment]
Does it work when you trigger Routine Speak directly with some hardcoded text?

**Comment by saviothecnic** [comment]
I have never used this option
you can post me an example so I try

**Comment by bbindreiter** [comment]
Add Inject Node and connect it to another Routine Speak node in which you've set some static text for Alexa to speak (Hello or something). If it works it's your flow, if not some Alexa/Node-Red config ain't working.

**Comment by saviothecnic** [comment]
Ok I tried I attach photos so you tell me if I did well for the test
As you can see from success but I do not feel anything
While as already written if I give voice commands in input it works but as I said until 2 weeks ago it worked
Then all of a sudden it no longer works for me on the way out 
![ProvaAudioAlexa](https://user-images.githubusercontent.com/6697807/138489937-c46bfa1a-ae71-4a49-9a2b-38a16b1a0731.jpg)

**Comment by bbindreiter** [comment]
Does the light ring shine on your Alexa? Or does that stay off too?

What if you use `Speak at Volume` instead of `Speak`? Still nothing?

**Comment by saviothecnic** [comment]
No ring does not show signs of life
i also upgraded to
node-red-contrib-alexa-remote2-applestrudel 5.0.6

**Comment by bbindreiter** [comment]
Because you said it started to stop suddenly and already worked one additional thing that comes to my mind would be to delete your cookie file and go through authorization again.

**Comment by saviothecnic** [comment]
![ProvaAudioAlexa2](https://user-images.githubusercontent.com/6697807/138492621-c646fb11-1e33-465a-a2f4-db5a9de12197.jpg)

I also tried so and nothing
and ring shows no signs of life

**Comment by saviothecnic** [comment]
> Because you said it started to stop suddenly and already worked one additional thing that comes to my mind would be to >delete your cookie file and go through authorization again.

Very good friend the advice to delete alexa.cookie worked
Now my Alexa is really talking again. Thank you for your support

**Comment by andesse** [comment]
@bbindreiter thanks that you keep everything up to date! Since I use this contrib everything with Alexa is flawless! Schönes Wochenende! :)
